(function () {
  'use strict';
  angular.module('pb.core', [
    'ngCookies',
    'ngAnimate',
    'ngResource',
    'ngSanitize',
    'hljs',
    'ui.router',
    'headroom',
    'angular-loading-bar',
    'pascalprecht.translate',
    'tmh.dynamicLocale',
    'toggle-switch',
    'toastr',
    'ui.bootstrap',
    'ui.utils',
    'ui-rangeSlider',
    'chart.js',
    'stpa.morris',
    'daterangepicker',
    'angularMoment',
    'angularUtils.directives.dirPagination',
    'infinite-scroll',
    'datatables',
    'datatables.bootstrap',
    'datatables.buttons',
    'xeditable',
    'angularChart',
    'duScroll',
    'ui.select',
    'ngTagsInput',
    'slickCarousel',
    'ngFileUpload',
    angularDragula(angular),
    'pb.ds.components'
  ]);
})();
